project:
  type: website
  output-dir: docs
  preview:
    port: 167
    browser: true
    navigate: true
  render: 
    - "*.qmd"
    - "!omit/"
    - "!examples/"
    - "!exercises"
    - "!data/building"
    - "!content_"
    - "!syllabus/building/"
    - "!syllabus/syllabus2.qmd"
    - "!modules/module_starter_page.qmd"
    - "!modules/intro_to_ggplot.qmd"
    #- "!modules/hello.qmd"
    - "!modules/building"
#    - "!modules/" # Note regarding !, if try to render with an ignore, will get ERROR: TypeError: Cannot convert undefined or null to object 
#    - "!slides/"
    - "!exercises/building/"
    - "!homework/building/"
    

website:
  title: "**PSYC167**"
  navbar:
    left:
      - text: "**Home**"
        file: index.qmd
      - text: "**Syllabus**"
        file: syllabus/syllabus.qmd
      #- text: "Textbook"
      #  href: https://psyteachr.github.io/ads-v2
      - text: "**Modules**"
        file: modules/index.qmd
#      - text: "Content"
#        file: modules/index.qmd
#      - text: "**Slides**"
#        #file: slides/index.qmd
#        menu:
#          - text: Topic 1
#            href: slides/sample_pres.qmd
#          - text: Topic 2
#            href: slides/sample_pres.qmd
      #- text: "Compendium"
      #  file: compendium/index.qmd
#      - text: "**Exercises**"
#        file: exercises/exercises.qmd
      #- text: "**Readings**"
      #  href: resources/dataviz_readings.qmd
      - text: "**Homework**"
        #file: slides/index.qmd
        menu:
          - text: HW 1
            href: homework/EX01.pdf
          - text: HW 2
            href: homework/HW02.Rmd
          - text: HW 3
            href: homework/HW03.Rmd
#          - text: HW 4
#            href: homework/HW04.Rmd
#          - text: HW 5
#            href: homework/HW05.Rmd
#          - text: HW 6
#            href: homework/HW06.Rmd
#          - text: HW 7
#            href: homework/HW07.Rmd
#          - text: HW 8
#            href: homework/HW08.Rmd
#          - text: HW 9
#            href: homework/HW09.Rmd
#          - text: HW 10
#            href: homework/HW10.Rmd
      - text: "**Data**"
        #file: slides/index.qmd
        menu:
          - text: cms-top-all-time-2023-swim.xlsx
            href: https://github.com/slicesofdata/dataviz23/raw/main/data/cms-top-all-time-2023-swim.zip
          - text: cleaned-cms-top-all-time-2023-swim.csv
            href: https://github.com/slicesofdata/dataviz23/raw/main/data/cleaned-cms-top-all-time-2023-swim.csv            
          - text: tfrrs.zip
            href: https://github.com/slicesofdata/dataviz23/raw/main/data/tfrrs.zip
     # - text: "Project"
#          - text: Overview 
#            href: project/project_overview.qmd
#          - text: Mid Semester Presentation
#            href: project/project_pres01.qmd
#          - text: Final Presentation
#            href: project/project_pres02.qmd
#          - text: Data
#            href: project/project_data.Rmd
      - text: "**Cheatsheets**"
        #file: slides/index.qmd
        menu:
          - text: RMarkdown
            href: cheatsheets/rmarkdown-2.0.pdf
          - text: 'Data Wrangling with {dplyr} and {tidyr}'
            href: https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf
          - text: Quarto (Publish and Share)
            href: https://rstudio.github.io/cheatsheets/html/quarto.html
          - text: 'String Manipulation with {stringr}'
            href: https://rstudio.github.io/cheatsheets/html/strings.html
          - text: 'Reading and Writing Data with {readr}'
            href: https://rstudio.github.io/cheatsheets/html/data-import.html
          - text: Data Science with RWorkflow
            href: cheatsheets/Data_Science_With_R_Workflow.pdf 
          - text: More Cheatsheets Here
            href: https://rstudio.github.io/cheatsheets/
      - text: "**DataViz Tools**"
        href: resources/dataviz_tools.qmd 

    right:
      - icon: github
        href: https://github.com/slicesofdata/dataviz23 #https://github.com/slicesofdata/psyc167
        aria-label: GitHub

  sidebar:
      #style: "floating"
      #collapse-level: 2
      #align: left
      #contents: auto
    - title: "Home"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - syllabus/syllabus.qmd
        - auto: modules
        
        #- compendium

    - title: "Modules zzzzz"
      style: "floating"
      collapse-level: 2
      align: left
      contents: modules

#    - title: "Exercises"
#      style: "floating"
#      collapse-level: 2
#      align: left

    - title: "Slides"
      style: "floating"
      collapse-level: 2
      align: left
#
#      contents: compendium      
#      contents: exercises
 #   - title: "Compendium"
#      style: "floating"
#      collapse-level: 2
#      align: left
#      contents: compendium

format:
  html:
    theme: css/styles.scss 
    css: [css/nav.css,css/styles.css]
    toc: true
    include-in-header: "css/fontawesome.html"
    #mainfont: arial #Nunito
    fontsize: 1.1rem # 1.2rem
#    linkcolor: "#096980"
#    monofont: courier new

#css: css/styles.scss

editor: source

