---
title: "Correlation Using R"
output: html_document
---

```{r echo = F}
#http://www.stat.ubc.ca/~jenny/STAT545A/block09_xyplotLattice.html
```

#1. Read in a data frame from a csv file#
```{r}
health <- read.csv("cdc.csv")
str(health)
```


#2. Take a look a the variables of interest#
```{r}
library("lattice") # load lattice

histogram(~health$weight)
histogram(~health$height)
```

#3. Plot the two variables in a scatterplot#
```{r}
# Women and Men
xyplot(health$height ~ health$weight)

# Add a linear fit line
xyplot(height ~ weight, data = health, 
       main = "Weight and Height",
       type = c("p", "r"))

# Subset by groups (a factor)
xyplot(height ~ weight, data = health, 
       main = "Weight and Height", 
       type = c("p", "r"), 
       groups = factor(gender, labels = c("Women", "Men")))

# Add group labels
xyplot(height ~ weight, data = health, 
       main = "Weight and Height",
       type = c("p", "r"),
       groups = factor(gender, labels = c("Women", "Men")),
       auto.key = list(columns = 2))

# Subset by a continuous variable
xyplot(height ~ weight, data = health, 
       main = "Weight and Height",
       groups = age)

# Plot separate plots for each level of a factor
xyplot(height ~ weight | genhlth, data = health, 
       main = "Weight and Height", 
       type = c("p", "r"))
```

#4. Calculate independent variance estimates#
```{r}
x <- var(health$weight)
y <- var(health$height)
```

#5. Calculate the covariance estimate#
```{r}
xycov <- cov(health$weight, health$height)
```

#6. Calculate the linear correlation using Pearson's *r*# 
```{r}
rxy <- xycov / sqrt(x * y)
rxy # take a look at the correlation value

r <- cor(health$weight, health$height)
r # take a look at the correlation value

# test r against a null hypothesis value of 0
cor.test(health$weight, health$height)
```

#7. Create vectors and combine into a Data Frame#
```{r}
failures <- c(5, 10, 3)
sleepless <- c(2, 3, 1)
failures; sleepless

df <- data.frame(failures, sleepless)
```

#7. Calculate Pearson's *r*#
```{r}
rsleep <- cor(df$failures, df$sleepless)
rsleep

# take a look at a scatterplot
xyplot(failures ~ sleepless, 
       data = df, 
       type = c("p", "r")) 

# test r against a null hypothesis value of 0
cor.test(df$failures, df$sleepless)
```
