---
title: "**Project**"
editor: visual
format:
  html:
    theme: cosmo
    css: css/styles.scss
    #fontcolor: white
    toc: true
---

```{r, message=FALSE, warning=FALSE, echo=FALSE, eval=TRUE}

```

## **Project Description**

For the data visualization project, your team will writ code in order to analyze data and create data visualizations in order to communicate a story that would address the client's interest in determining whether COVID has influenced athlete performance. Given the constraints of data to inform this specific question, the project will involve data exploration to tell a story about athlete performance. Given the client has little information about athlete performance, including data visualizations, this exploration allows for a healthy dose of flexibility in team creativity. This open element will also allow teams to develop ideas independently, thereby producing stories that will likely diverge wildly from each other, making the project an exciting foray into data storytelling for many students.


### **Project Roles**

Project roles help streamline events, assist delegation, allow for some accountability, and reduce workload overlap. Project roles are designed to help keep the project organized and reduce confusion about what project elements team members are taking on. Team roles should be decided upon in a way that maximizes member ability so that task demands are equal across team members. These roles provide some guidelines but do not obviate members from contributing to and participating in other tasks subsumed under specific roles. In other words, when the Project Manager falls ill, another team member should step up to facilitate any necessary communication between the liaison of me. Likewise, the Coding Lead would step in to help the Writing Lead revise writing when necessary. Similarly, the Writing Lead or Project Manager should help the Coding Lead with organizing code when appropriate. All team members have have the same goal, which is to develop, code, and communicate the project to the liaison. All members will code, organize, and write and may take lead on sections with which they are most familiar or most qualified in addressing.

If the team decides to create roles different from those suggested below, please just let me know.

**Suggested Roles:**

#### 1. *Project Manager (PM)*: The project manager helps with organization of the project and is the point person for communication.

-   Communicating with course faculty and liaison(s);
-   Scheduling and reminding the team meetings and meetings with liaison;
-   Assigning tasks to team members (with help from course professor is needed) and based on the project requirements;
-   Monitoring and keeping track of each member's project progress;
-   Motivating the team members on their task completion and future goals;
-   Dealing with any conflicts within the team and updating any concerns with course professor;
-   Coordinating team activities such as presentation dry runs;
-   Helping maintain equity of tasks across all team members, inclusion the PM;
-   The Project Manager is not responsible to reminding team members to complete their tasks or complete worklogs.

#### 2. *Reporting Lead (RL)*: The reporting lead(s) helps with organization of the reporting documents (e.g., slides, report) and revision of writing.

-   1 or 2 members
-   Planning, guiding, and leading report writing;
-   Doing background/external research on topic as relevant;
-   Assigning sections/chapters of documents to appropriate members;
-   Keeping track of the written progress;
-   Helping develop a data visualization story line;
-   Formatting, text, images, inline code (R code embedded in text), and tables on final document (RMarkdown for final report);
-   Proofreading/editing deliverable documents like slide presentation, written report, etc.;
-   The Reporting Team is not responsible to all writing. 

#### 3. *Coding Lead (CL)*: The coding lead(s) helps with organization and management of the project code elements (e.g., project, code, associated files, GitHub repo (recommended)).

-   1 or 2 members
-   Creating and maintaining organization of the project code (e.g., directories, sourced scripts, etc.)
-   Leading coding and code documenting;
-   Assigning technical tasks to other team members;
-   Keeping track of the progress of the technical tasks;
-   Helping other team members troubleshoot code (see also TA and course professor);\
-   Communicating with PM, liaison (during liaison meetings), and course professor regarding any technical needs and concerns;
-   Communicating with RL regarding messaging of coded results;
-   Maintaining GitHub repo (recommended, please see course professor for assistance);
-   The Coding Team is not responsible for all coding. 

Based on abilities and interests of team members, the team should determine how many individuals to assign to a given role, or determine other appropriate roles given the abilities of the team members. There should be unanimity in these decisions. I will not assign you to roles. 


## **Project Grading**

-   Quality of project deliverable documents (e.g., organization, coherence, story, coding clarity/organiation, plots, etc.)
-   Professionalism (e.g., liaison meeting etiquette and responsibility, timely discord communication, non-tardy attendance at weekly team meeting, weekly worklogs, feedback from liaison, etc.)
-   Peer evaluation (e.g., contributions, team player, etc.)

Note: Liaison's will also participate in evaluating all teams. The team with the most impressive project (e.g., most clear, most useful and actionable, most interesting, most thought provoking, etc.) will receive bonus points.

## **Presentation**

### **Presentation Characteristics**

1.  *Clarity*: well-explained; easy to follow/understand; ability to communicate points effectively

2.  *Organization*: structured logically; ability to walk audience through the data journey and communicate a story interpretation about data

3.  *Thoroughness*: all relevant issues discussed thoroughly

4.  *Presentation Style*: degree of preparedness and polish in presentation; smooth and rehearsed; minimum of reading; well-paced; slide quality


### **Presentation Tips**

-   Speak to your audience. Look them in the eyes, tell them about the journey. In other words, don't just read from your slides.
-   Do not overwhelm your audience with too much information, especially verbal information. Doing so causes people to read your slides or look at slide content you are not talking about at the moment. You are the presenter and your slides are your visual aides used to support what you communicate. Elaboration can occur in the written deliverable.
    -   Present slides topically; do not mix unrelated content; use relevant headers, etc.
    -   Present summary points on slides rather than full sentences. Communicate to your audience in sentences but don't present complete sentences on slides unless imperative for communicating a specific point.
    -   Present each point separately; do not present all slide content at once (e.g., points a, b, c); communicate specific points (e.g., a) to your audience. Presenting all points at once prevents your audience from paying attention to you and causes cognitive interference/distraction.
    -   Use a tool (e.g., pointer, etc.) to direct attention to necessary elements of slides, especially when a slide contains multiple pieces of information. Doing so will reduce unnecessary confusion from some audience members because they will not be looking at the incorrect content.
-   Introduce team members, their role, etc. when "passing the the mic". Your client should be reminded of who the team member is and what their role was.


## **Weekly Worklog/Report**

Tracking individual and team goals weekly ensures progress toward the goal, commitment to the project, accountability for oneself, and a record of accomplishments.

The Project Manager should inquire with the team about the best way to submit worklogs or transparency and review. This could be a Google Doc File, a spreadsheet, or even a Google From that contains questions to answer, which then get dumped into a Google Spreadsheet for all to review. 


### **Frequency of Worklog**

Worklogs are to be completed by *end-of-day following the team meeting*, after communicating future goals (distributed equally) to other team members. Please make public for me to review.


### **Contents of Worklog**

Worklogs should contain information about the reporting date, the team member reporting, that member's previous week accomplishments, and that member's future week accomplishments. 

1. For the past week, I accomplished the following specific goals for my team:
+ This...
+ That...
+ And the other...

2. For this past week, the number of hours allocated toward those goals was: ___

3. For this coming week, my specific goals for the team include:

* This...
* That...
* And the other...

4. If relevant, any items to discuss with liaison.







