---
title: "**Hello, Quarto**"
author: "Gabriel I. Cook"
#date: "`r Sys.Date()`"
date: "`r format(Sys.time(), '%d %B, %Y')`"

#format:
#  html:
#    code-fold: true
#    code-tools: true

editor: visual
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#| label: load-packages
#| include: false
#file.remove(here::here("modules", "*hello.html"))
library(tidyverse)
library(palmerpenguins)
library(ggplot2)
library(magrittr)
```

```{r}
#library(palmerpenguins)
#head(palmerpenguins::penguins)
```

``` r
#| label: plot-penguins
#| warning: false
#| echo: false

ggplot(penguins, 
       aes(x = flipper_length_mm, y = bill_length_mm)) +
  geom_point(aes(color = species, shape = species)) +
  scale_color_manual(values = c("darkorange","purple","cyan4")) +
  labs(
    title = "Flipper and bill length",
    subtitle = "Dimensions for penguins at Palmer Station LTER",
    x = "Flipper length (mm)", y = "Bill length (mm)",
    color = "Penguin species", shape = "Penguin species"
  ) +
  theme_minimal()
```

```{r}
penguins %>%
  ggplot(., 
       aes(x = flipper_length_mm, y = bill_length_mm)) +
  geom_point(aes(color = species, shape = species)) +
  scale_color_manual(values = c("darkorange","purple","cyan4")) +
  labs(
    title = "Flipper and bill length",
    subtitle = "Dimensions for penguins at Palmer Station LTER",
    x = "Flipper length (mm)", y = "Bill length (mm)", scolor = "Penguin species", shape = "Penguin species"
  ) +
  theme_minimal()
```



```{r}
#library(ggplot2)

#dat <- data.frame(cond = rep(c("A", "B"), each=10),
#                  xvar = 1:20 + rnorm(20,sd=3),
#                  yvar = 1:20 + rnorm(20,sd=3))

#ggplot(dat, aes(x=xvar, y=yvar)) +
#  geom_point(shape=1) + 
#  geom_smooth() 
```

