---
title: "**Color and Color Palette**"
#description: |
author: "Gabriel I. Cook"
date: "`r format(Sys.time(), '%d %B, %Y')`"

# https://quarto.org/docs/reference/formats/html.html

format: 
  html:    
    theme: css/styles.scss
    toc: true                   # include a table of contents
    toc-depth: 3
    toc-location: right          # body/left/right
    toc-expand: true
    number_sections: true       # enumerate sections flagged with #
    code_fold: true             # allow option to show/ture/false code
    number-depth: 1

#    code-fold: true
    #css: [css/nav.css,css/styles.css]
    
    #backgroundcolor: blue
  #html_document:               

#theme: cosmo #quartz
    #css: css/home.css
    #fontcolor: black
    #page-layout: full
    #css: [css/nav.css,css/styles.css]
    
#editor_options: 
#  chunk_output_type: console

#output: 
#  quarto::html_document:

execute: 
#  eval: true
#  echo: true
#  output: 
#  warning: true
#  error: true
#  include: true
#  cache: true
  freeze: true  # never re-render during project render 
  #freeze: auto  # re-render only when source changes
    
---


```{r notes, include=FALSE}
# to hide code, in plot block, use  #| echo: true

# for plots:
 # add  | fig-cap: "caption"  
 # add #| label: the the name of the figure label

# https://quarto.org/docs/computations/execution-options.html


```

# one

link to other location 
[syllabus](syllabus/syllabus.qmd)

## two 

ljljlasfd

# one again


## Load Libraries

```{r libraries}
#| warning: false
#| message: false
library(ggplot2)
library(here)
library(tidyverse)
library(magrittr)
```

## Color-Related Libraries

```{r color-libraries}

library(monochromeR)
```

## Creating Color Palettes


```{r generate-palette}
monochromeR::generate_palette("#db5a05", 
    blend_colour = "red", 
    n_colours = 3, 
    view_palette = TRUE)
```

```{r go-darker}
monochromeR::generate_palette("#3c6b30", "go_darker", 
   n_colours = 2, 
   view_palette = TRUE)
```

``` {r go-lighter}

monochromeR::generate_palette("#0C1509", "go_lighter", 
n_colours = 6, view_palette = TRUE)

```



## Functions

Get the class repo using `usethis::use_course()` and source it.

```{r external-functions}
#suppressWarnings(lapply(c("data", "r", "r/src", "figs", "docs"), FUN = function(x) dir.create(here::here(x))))

usethis::use_course(url = "https://github.com/slicesofdata/dataviz167/archive/master.zip", 
                    destdir = here::here("r", "src"))
#                    
if (file.exists(here::here("r", "src", "dataviz-main167", "dataexternal_functions.R"))) source(here::here("r/src/dataviz167-main", "external_functions.R"))
```


## Air Quality

@fig-label further explores the impact of temperature on ozone level.

```{r}
#| label: fig-label
#| warning: false
#| fig-cap: "caption"  
ggplot(airquality, aes(Temp, Ozone)) + 
  geom_point() + 
  geom_smooth(method = "loess")
```


