---
title: "****"
#description: |
author: "Gabriel I. Cook"
date: "`r format(Sys.time(), '%d %B, %Y')`"

# https://quarto.org/docs/reference/formats/html.html

format: 
  html:    
    theme: css/styles.scss
    toc: true                   # include a table of contents
    toc-depth: 3
    toc-location: right          # body/left/right
    toc-expand: true
    number_sections: true       # enumerate sections flagged with #
    code_fold: true             # allow option to show/ture/false code
    number-depth: 1

#    code-fold: true
    #css: [css/nav.css,css/styles.css]
    
    #backgroundcolor: blue
  #html_document:               

#theme: cosmo #quartz
    #css: css/home.css
    #fontcolor: black
    #page-layout: full
    #css: [css/nav.css,css/styles.css]
    
#editor_options: 
#  chunk_output_type: console

#output: 
#  quarto::html_document:

execute: 
#  eval: true
#  echo: true
#  output: 
#  warning: true
#  error: true
#  include: true
#  cache: true
  freeze: true  # never re-render during project render 
  #freeze: auto  # re-render only when source changes
    
---


```{r notes, include=FALSE}
# to hide code, in plot block, use  #| echo: true

# for plots:
 # add  | fig-cap: "caption"  
 # add #| label: the the name of the figure label

# https://quarto.org/docs/computations/execution-options.html


```

# one

link to other location 
[syllabus](syllabus/syllabus.qmd)

## two 


## Load Libraries

```{r libraries}
#| warning: false
#| message: false
library(ggplot2)
library(here)
library(tidyverse)
library(magrittr)
#library(ggtext)
#library(glue)
```

## Functions

Get the class repo using `usethis::use_course()` and source it.

```{r external-functions}
#suppressWarnings(lapply(c("data", "r", "r/src", "figs", "docs"), FUN = function(x) dir.create(here::here(x))))

#usethis::use_course(url = "https://github.com/slicesofdata/dataviz167/archive/master.zip", 
#                    destdir = here::here("r", "src"))
#                    
if (file.exists(here::here("r", "src", "dataviz-main167", "dataexternal_functions.R"))) source(here::here("r/src/dataviz167-main", "external_functions.R"))
```


[Beautifully annotated: enhancing your ggplots with text](https://cararthompson.github.io/rl-cambridge-beautifully-annotated/beautifully-annotated_RLadiesCam.html#/title-slide)

```{r}
#| label: fig-label
#| warning: false
#| fig-cap: "caption"  

```

```{r}
# Libraries ----
library(tidyverse)
library(glue)

# Data source
library(datasets) #ToothGrowth

# Annotations
library(extrafont)
library(ggtext)


ToothGrowth %>%
  mutate(supplement = case_when(supp == "OJ" ~ "Orange Juice", supp == "VC" ~ "Vitamin C", TRUE ~ as.character(supp))) %>%
  group_by(supplement, dose) %>%
  summarise(mean_length = mean(len)) %>%
  mutate(categorical_dose = factor(dose)) %>%
  ggplot(aes(x = categorical_dose,
             y = mean_length,
             fill = supplement)) +
  geom_bar(stat = "identity",
           position = "dodge",
           colour = "#FFFFFF", 
           size = 2) + 
  labs(x = "Dose",
       y = "Mean length (mm)",
       title = "In smaller doses, Orange Juice was associated with greater mean tooth growth,
compared to equivalent doses of Vitamin C",
       subtitle = "With the highest dose, the mean recorded length was almost identical.") +
  scale_fill_manual(values = vit_c_palette) +
  facet_wrap(supplement ~ ., ncol = 1) +
  theme_minimal()

# Export ----
ggsave(labelled_plot, 
       filename = here::here("figs", "annotated_penguins.png"), 
       dpi = 400, width = 12, height = 9,
       bg = "#ffffff")
```

