---
title: "Team-Based Cognitive Task Assessment"
author: ""
#date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


For presentation format, review previous handout on the project.


# **Project Evaluation**

You will be evaluated on your team's ability to convey the steps taken to produce your deliverable for the Stroop data to your audience (the client). Your individual performance and contributions will be considered toward the evaluation. Reflect back on the steps taken to achieve the project goals. Your team should communicate those steps as the final deliverable is dependent on them. Teams taking different approaches will end up with different data and potentially different stories. Include code where appropriate to communicate how you achieved your goals.


## *Data Cleaning and Variable Creation*

1. Communicate steps taken to clean data to fulfill sub-goals

2. Communicate how you modified variables and/or computed variables of interest 



## *Data Summary: Story Telling with Tables or Numbers*

1. Communicate how you calculated and/or obtained summary metrics

2. Provide data summaries for performance metrics of interest

3. Thoroughness of communicating data summaries: data summaries convey information about average performance of the sample, the sample size, and ideally some measure of variability within the sample

4. Above and beyond: communication of novel or deeper-level data inquiries that communicate interesting elements or relationships in the data



## *Data Visualizations: Story Telling with Pictures*

1. Convey performance metrics using appropriate data visualizations 

2. Communicate how you obtained the data visualizations

3. Appropriateness and quality of plots: data visualizations communicate an appropriate and comprehensive story about the data; visualization convey information about sample performance as well as 

4. Above and beyond: communication of novel or deeper-level data visualizations that communicate interesting elements or relationships in the data



## *Presentation Characteristics*

1. *Clarity*: well-explained; easy to follow/understand; ability to communicate points effectively

2. *Organization*: structured logically; ability to walk audience through the data journey and communicate a story interpretation about data

3. *Thoroughness*: all relevant issues discussed thoroughly

4. *Presentation Style*: degree of preparedness and polish in presentation; smooth and rehearsed; minimum of reading; well-paced; slide quality



## *Weekly Progress Report Logs*

Demonstration of weekly goals and progress. Timeliness and submission of weekly report logs.



## *Team and Team Member Evaluation*

1. Evaluation of personal contributions toward the project as evaluated by other team members (claims partially validated using on-time weekly report submissions). 

2. The audience (your client) will also provide an overall review for the team and individual team members.  


## *Self Evaluation*

Evaluation of your personal contributions toward the project as evaluated by yourself (claims partially validated using on-time weekly report submissions).


# **Reproducibility**

A well-organized project is easily reproducible by others. Class readings have been taken largely from a text on reproducible research, so quite naturally, others should be able to evaluate code and reproduce your results, if desired. Knit HTML versions of R Markdown files allow others to evaluate and validate the code without the effort of running the code themselves. We have used R Markdown throughout the semester for homework assignments and class exercises in order to illustrate code execution, create reports, and communicate tables/data visualizations. These files also allow others to reproduce data summaries and plots easily. As anticipated, an knit/html .Rmd file of the project containing the coded steps taken to produce the final deliverable should be included. This should be easy to produce for organized teams and projects. 


# **Presentation Tips**

1. Speak to your audience. Look them in the eyes, tell them about the journey. In other words, don't just read from your slides. 

2. Do not overwhelm your audience with too much information, especially verbal information. Doing so causes people to read your slides or look at slide content you are not talking about at the moment. You are the presenter and your slides are your visual aides used to support what you communicate. 

a. Present points rather than full sentence content. Speak in sentences but don't present complete sentences on slides unless imperative to a point.

b. Reveal points as you present each point separately. Do no present all slide content (e.g., points a, b, c) communicating specific points (e.g., a). Doing so prevents your audience from paying attention to you; causes cognitive interference.

c. Use a tool (e.g., pointer, finger, etc.) to direct attention to necessary elements, especially when a slide contains multiple pieces of information. Doing so will cause unnecessary confusion from some audience members because they will be looking at the incorrect content.

d. 




# **Stakeholders**

The stakeholders for your project deliverable include your friends whose data you and your peers are collecting for the exercises.  


# **Data Visualizations**

Keep in mind that you may need to create, and use, different data frames for creating plots. The plot will represent the goal of the visualization.


## A. *Plot 1 (responded-level data)*

1.	For each respondent, plot a box-plot geometry of response latencies for all congruent and all incongruent trials. Consider how you might plot the same plot separately for each respondent. The goal is to visualize the pattern of congruent verses incongruent response latencies for each respondent. After all, these patterns will be combined when you create and plot group-level data, so looking at each respondent individually is useful information.  

2.	Add a point-plot geom layer to see all of the points for all congruent and incongruent trials overlayed onto the box plots. To make the congruent and incongruent trials pop visually and just for practice, make the congruent and incongruent points appear in different colors. Make sure to address overplotting.


## B. *Plot 2 (group-level summarized data)*

1.	Plot a group-level point-plot geom representing the *means* of all  respondent's congruent and incongruent response latencies.  

2.	Add a box plot geom that represents the same data


## C. *Plot 3*

1.	Using the means for each respondent, plot histogram- or density-plot geoms for congruent and incongruent trials. Changing the color of the congruent and incongruent trials will allow you to easily distinguish the two visualizations. Changing transparency may also be helpful.



# *Dealing with Outliers*

A.	Visually

1. Examine using a visualization whether there are any outliers in your group-level data. Participants who do not respond like others may influence your interpretation and model you test later. 

B.	Computationally 

1. Mathematically examine outliers in your group-level data by calculating z scores for both the congruent and incongruent trials separately. 

2. If any respondent's repsonse latencies are 3 (or 2.5) standard deviations above or below the group-level mean for either the congruent and incongruent trials, flag them as an outlier by creating a new variable. 

C.	Replot your visualiztion that dislays group-level data using both box- and point-plot geoms for congruent and incongruent trials but now after filtering out outliers (if there are any).



# *Group-Level Summaries in a Table*

1. Summarize the data so that you present in a table (not a plot) the group-level means, standard deviations, and sample sizes for the congruent and incongruent trials. Keep in mind that a repeated-measures design like this should have sample sizes that are equal for the levels of that variable, so your sample sizes should be equal.


2. 

