---
title: "**quarto_ggplot_starter**"
#description: |
author: "Gabriel I. Cook"
date: "`r format(Sys.time(), '%d %B, %Y')`"

# https://quarto.org/docs/reference/formats/html.html

format: 
  html:    
    theme: css/styles.scss
    toc: true                   # include a table of contents
    toc-depth: 3
    toc-location: right          # body/left/right
    toc-expand: true
    number_sections: true       # enumerate sections flagged with #
    code_fold: true             # allow option to show/ture/false code
    number-depth: 1

#    code-fold: true
    #css: [css/nav.css,css/styles.css]
    
    #backgroundcolor: blue
  #html_document:               

#theme: cosmo #quartz
    #css: css/home.css
    #fontcolor: black
    #page-layout: full
    #css: [css/nav.css,css/styles.css]
    
#editor_options: 
#  chunk_output_type: console

#output: 
#  quarto::html_document:

execute: 
#  eval: true
#  echo: true
#  output: 
#  warning: true
#  error: true
#  include: true
#  cache: true
  freeze: true  # never re-render during project render 
  #freeze: auto  # re-render only when source changes
    
---


```{r notes, include=FALSE}
# to hide code, in plot block, use  #| echo: true

# for plots:
 # add  | fig-cap: "caption"  
 # add #| label: the the name of the figure label

# https://quarto.org/docs/computations/execution-options.html


```

# one


## two 

ljljlasfd

### three

asfasfsdf

# one again


## Load Libraries

```{r libraries}
library(ggplot2)
```


## Air Quality

@fig-label further explores the impact of temperature on ozone level.

```{r}
#| label: fig-label
#| warning: false
#| fig-cap: "caption"  
ggplot(airquality, aes(Temp, Ozone)) + 
  geom_point() + 
  geom_smooth(method = "loess")
```


