---
title: ""
author: ""
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls(all.names = TRUE))      # remove objects in R

source("https://pastebin.com/raw/8mXH02yg")   # run and comment out after knitting
source("https://pastebin.com/raw/97NNTTzu")   # run to include in function definitions

# set the paths for project, script, and data dirs
proj_dir <- gsub("GCDS.*.Rmd", "GCDS", get_ActivePath())
proj_name = ""
r_dir    <- paste(proj_dir, "r", sep = "/")    # r subdir
data_dir <- paste(proj_dir, "data", sep = "/") # data subdir
if ( proj_name != "" & !dir.exists(paste(proj_dir, proj_name, sep = "/")) ) {
  # create project dir
  suppressWarnings(dir.create(paste(proj_dir, proj_name, sep = "/")))
  r_dir <- gsub("/r", paste0("/", proj_name, "/r"), r_dir)
  data_dir <- gsub("/data", paste0("/", proj_name, "/data"), data_dir)
  # create sub directories
  suppressWarnings(dir.create(r_dir))
  suppressWarnings(dir.create(data_dir)) }
```

```{r}
library(dplyr)
library(magrittr)
```


```{r}
iq <- as.integer(rnorm(1000, 100, 15))
sex <- rep( c("F", "M"), times = 500)
id <- c(1:1000)

DF <- data.frame(Id = id, 
                 Sex = sex, 
                 Iq = iq)

head(DF)

str(DF)

names(DF) 

DF$Sex <- as.factor(DF$Sex)

DF[ , "Sex"]

str(DF)

levels(DF$Sex)

DF <- DF %>%
  mutate(., 
         Sex_fact = as.factor(Sex),
         New_var1 = 0,
         New_var2 = Iq/2,
         New_var3 = case_when(
           Iq <= 75 ~ 1,
           Iq > 76 & Iq <= 115 ~ 2,
           Iq > 115 ~ 3
         ),
         New_var4 = ntile(Iq, 4)
         )


head(DF)

DF %>% 
  mutate(., across(.cols = starts_with("New"), scale, 
                   .names = "z_{.col}")
         ) %>%
  select(., starts_with("z")) %>%
  head(.)

```



