---
title: "GCDS: Model Training ***********************"
#author: "gcook"
#date: "`r Sys.Date()`"
output: 
  html_document: 
    toc: yes
    number_sections: yes
    highlight: pygments
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE, include=FALSE}
rm(list = ls(all.names = TRUE))

# load externals
# source("https://pastebin.com/raw/8mXH02yg") # install libraries
source("https://pastebin.com/raw/b63hB7Hj")   # functions

# some objects to work with
this_rmd_path = rstudioapi::getActiveDocumentContext()$path
proj_name = ""
proj_dir <- gsub("r/.*.Rmd","", this_rmd_path)
r_dir <- paste0(proj_dir, "r/")
data_dir <- paste0(proj_dir, "data/")
```

Load libraries.   

```{r message=FALSE, warning=FALSE}
# load some libraries
library(tidyverse)
library(magrittr)
library(GGally)
library(DataExplorer)

#data.table
#dplyr
#ggplot2
#caret
#e1071
#xgboost
#randomForest
```


```{r message=FALSE, warning=FALSE}
DAT <- read_csv(paste0(data_dir, "psa001_agg.csv")) # face data

DAT2 <- read_csv(paste0(data_dir, "pets.csv"))   # pet data also at DSRR

BG <- read_csv(paste0(data_dir,"Games_Survey_numeric_gcook_cleaned.csv"))
```


View data in html? 

```{r}
# uses the function defined at the top of the file
view(BG, show = 10)
```


```{r message=FALSE, warning=FALSE, include=FALSE}
DAT <- DAT %>% 
  # create new variables based on characters
  mutate(sex  = ifelse(grepl("F", stim_id), "Female", "Male"), # using ifelse()
         race = case_when(grepl("B", stim_id) ~ "Black",       # easier using dplyr::case_when()
                          grepl("A", stim_id) ~ "Asian",
                          grepl("W", stim_id) ~ "White",
                          grepl("L", stim_id) ~ "Latino"
                          )
  ) %>%
  # dplyr::select(stim_id, attractive, caring, intelligent, mean, unhappy) %>%
  select(-stim_id) %>%                                # remove 1 ,  - means subtract out
  select(-c(responsible, sociable, weird, emostable)) # remove multiple, -c()
```


